spring:
  datasource:
    url: jdbc:mysql://localhost:3336/mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8081
